CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description VARCHAR(255),
                          price NUMERIC(38, 2) NOT NULL,
                          sku VARCHAR(255) NOT NULL UNIQUE
);